name: owner_resort_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.1
  file_picker: 8.1.4
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_polyline_points: ^2.1.0
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  geocode: ^1.0.3
  go_router: ^14.6.2
  google_maps_flutter: ^2.10.0
  http: ^1.3.0
  intl: ^0.20.1
  location: ^6.0.2
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  firebase_messaging: ^15.2.1
  flutter_rating: ^2.0.2
  flutter_local_notifications: ^18.0.1
  table_calendar: ^3.2.0
  fl_chart: ^0.70.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/